version: '3'
services:
  web:
    build: .
    ports:
     - 8080:8080
    links:
     - mongo
    depends_on:
     - mongo
    environment:
     SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/db
  mongo:
    image: mongo:latest
    ports:
     - 27017